package store

import (
	"database/sql"
	"errors"
	"fmt"
)

// gradingSystemSeed describes a built-in grading system as a list of belts and
// the stripe range each belt is graded across. Ranks are generated by expanding
// every belt over degrees 0..maxDegree (ADR-0001, Option B): the belt name is
// the rank's group, the stripe count its degree, and both are descriptive only.
type gradingSystemSeed struct {
	name      string
	belts     []string
	maxDegree int
}

// seedSystems is the reference data for issue 03. A rare 5th BJJ stripe is left
// out deliberately: the data-driven model makes adding one rank trivial, so
// clubs that use it add it where it actually applies rather than by default.
var seedSystems = []gradingSystemSeed{
	{
		name: "BJJ Kids",
		belts: []string{
			"White", "Grey-White", "Grey", "Grey-Black",
			"Yellow-White", "Yellow", "Yellow-Black",
			"Orange-White", "Orange", "Orange-Black",
			"Green-White", "Green", "Green-Black",
		},
		maxDegree: 3,
	},
	{
		name:      "BJJ Adult",
		belts:     []string{"White", "Blue", "Purple", "Brown", "Black"},
		maxDegree: 4,
	},
}

// Seed inserts the built-in grading systems and their ranks where absent. It is
// idempotent — existing systems and ranks are left untouched — so it is safe to
// call on every boot. Reference data only: it never touches athletes or
// promotions. The whole seed runs in one transaction so a failure leaves no
// half-seeded system behind.
func Seed(db *sql.DB) error {
	tx, err := db.Begin()
	if err != nil {
		return fmt.Errorf("begin seed tx: %w", err)
	}
	defer tx.Rollback()

	// The slice order is the display order: seedSystems lists kids before adult,
	// so its index becomes each system's sort_order (progression order).
	for order, sys := range seedSystems {
		gsID, err := ensureGradingSystem(tx, sys.name, order)
		if err != nil {
			return err
		}
		// sort_order is a running counter across the whole system, so belts and
		// their stripes list in belt-then-degree order (display only, ADR-0001).
		order := 0
		for _, belt := range sys.belts {
			for degree := 0; degree <= sys.maxDegree; degree++ {
				if err := ensureRank(tx, gsID, belt, degree, order); err != nil {
					return err
				}
				order++
			}
		}
	}
	return tx.Commit()
}

// ensureGradingSystem returns the id of the named system, inserting it if it
// does not yet exist. On both paths it sets sort_order to order, so re-seeding
// after the column was added (migration 00003) corrects the display order of
// systems that predate it.
func ensureGradingSystem(tx *sql.Tx, name string, order int) (int64, error) {
	var id int64
	err := tx.QueryRow(`SELECT id FROM grading_systems WHERE name = ?`, name).Scan(&id)
	switch {
	case err == nil:
		if _, err := tx.Exec(`UPDATE grading_systems SET sort_order = ? WHERE id = ?`, order, id); err != nil {
			return 0, fmt.Errorf("update grading system order %q: %w", name, err)
		}
		return id, nil
	case errors.Is(err, sql.ErrNoRows):
		res, err := tx.Exec(`INSERT INTO grading_systems (name, sort_order) VALUES (?, ?)`, name, order)
		if err != nil {
			return 0, fmt.Errorf("insert grading system %q: %w", name, err)
		}
		id, err := res.LastInsertId()
		if err != nil {
			return 0, fmt.Errorf("last insert id for grading system %q: %w", name, err)
		}
		return id, nil
	default:
		return 0, fmt.Errorf("lookup grading system %q: %w", name, err)
	}
}

// ensureRank inserts the rank for one belt-and-degree if it is not already
// present. Existing rows are left as-is, including their sort_order, so a
// re-seed neither duplicates nor reorders ranks.
func ensureRank(tx *sql.Tx, gsID int64, belt string, degree, order int) error {
	name := rankName(belt, degree)
	var exists int
	err := tx.QueryRow(
		`SELECT 1 FROM ranks WHERE grading_system_id = ? AND name = ?`, gsID, name,
	).Scan(&exists)
	switch {
	case err == nil:
		return nil // already seeded
	case errors.Is(err, sql.ErrNoRows):
		_, err := tx.Exec(
			`INSERT INTO ranks (grading_system_id, name, rank_group, degree, sort_order)
			 VALUES (?, ?, ?, ?, ?)`,
			gsID, name, belt, degree, order,
		)
		if err != nil {
			return fmt.Errorf("insert rank %q: %w", name, err)
		}
		return nil
	default:
		return fmt.Errorf("lookup rank %q: %w", name, err)
	}
}

// rankName renders a human display name for a belt at a given stripe degree,
// e.g. "White" (plain belt), "White, 1 stripe", "White, 2 stripes". The name is
// what a promotion targets; group/degree are the descriptive breakdown.
func rankName(belt string, degree int) string {
	switch degree {
	case 0:
		return belt
	case 1:
		return belt + ", 1 stripe"
	default:
		return fmt.Sprintf("%s, %d stripes", belt, degree)
	}
}
