package store

import (
	"database/sql"
	"errors"
	"fmt"
	"slices"
)

// gradingSystemSeed describes a built-in grading system as a list of belts and
// the stripe range each belt is graded across. Ranks are generated by expanding
// every belt over degrees 0..maxDegree (ADR-0001, Option B): the belt name is
// the rank's group, the stripe count its degree, and both are descriptive only.
// slug is the system's identity outside the database (ADR-0006) and is written
// here by hand — deriving it from the name would make the identity translatable
// and could collide with the reserved "none".
type gradingSystemSeed struct {
	name      string
	slug      string
	belts     []string
	maxDegree int
}

// seedSystems is the reference data for issue 03. A rare 5th BJJ stripe is left
// out deliberately: the data-driven model makes adding one rank trivial, so
// clubs that use it add it where it actually applies rather than by default.
var seedSystems = []gradingSystemSeed{
	{
		name: "BJJ Kids",
		slug: "bjj-kids",
		belts: []string{
			"White", "Grey-White", "Grey", "Grey-Black",
			"Yellow-White", "Yellow", "Yellow-Black",
			"Orange-White", "Orange", "Orange-Black",
			"Green-White", "Green", "Green-Black",
		},
		maxDegree: 3,
	},
	{
		name:      "BJJ Adult",
		slug:      "bjj-adult",
		belts:     []string{"White", "Blue", "Purple", "Brown", "Black"},
		maxDegree: 4,
	},
}

// SeededRankGroups lists every rank_group the built-in systems use, in seed
// order and deduplicated (White appears in both systems). It is exported for the
// view's guards: both the belt colour table and the localized colour words must
// cover every group the seed writes, and deriving both from here is what keeps a
// colour added below from being missed by either (ADR-0009).
func SeededRankGroups() []string {
	var groups []string
	for _, sys := range seedSystems {
		for _, belt := range sys.belts {
			if !slices.Contains(groups, belt) {
				groups = append(groups, belt)
			}
		}
	}
	return groups
}

// seed inserts the built-in grading systems and their ranks where absent, and
// brings the ones already there back in line with the definitions above. It is
// idempotent — a second run over an untouched database changes nothing — which is
// what lets Open run it on every open. Reference data only: it never touches
// athletes or promotions. The whole seed runs in one transaction so a failure
// leaves no half-seeded system behind.
func seed(db *sql.DB) error {
	tx, err := db.Begin()
	if err != nil {
		return fmt.Errorf("begin seed tx: %w", err)
	}
	defer tx.Rollback()

	// The slice order is the display order: seedSystems lists kids before adult,
	// so its index becomes each system's sort_order (progression order).
	for order, sys := range seedSystems {
		gsID, err := ensureGradingSystem(tx, sys.name, sys.slug, order)
		if err != nil {
			return err
		}
		// sort_order is a running counter across the whole system, so belts and
		// their stripes list in belt-then-degree order (display only, ADR-0001).
		order := 0
		for _, belt := range sys.belts {
			for degree := 0; degree <= sys.maxDegree; degree++ {
				if err := ensureRank(tx, gsID, belt, degree, order); err != nil {
					return err
				}
				order++
			}
		}
	}
	return tx.Commit()
}

// ensureGradingSystem returns the id of the named system, inserting it if it
// does not yet exist. On both paths it sets sort_order and slug, so re-seeding
// after either column was added (migrations 00003, 00004) corrects the systems
// that predate it. The lookup stays on the name: it is the column that has
// always been unique, and a system that predates the slug has none to match on.
func ensureGradingSystem(tx *sql.Tx, name, slug string, order int) (int64, error) {
	var id int64
	err := tx.QueryRow(`SELECT id FROM grading_systems WHERE name = ?`, name).Scan(&id)
	switch {
	case err == nil:
		if _, err := tx.Exec(`UPDATE grading_systems SET sort_order = ?, slug = ? WHERE id = ?`, order, slug, id); err != nil {
			return 0, fmt.Errorf("update grading system order %q: %w", name, err)
		}
		return id, nil
	case errors.Is(err, sql.ErrNoRows):
		res, err := tx.Exec(`INSERT INTO grading_systems (name, slug, sort_order) VALUES (?, ?, ?)`, name, slug, order)
		if err != nil {
			return 0, fmt.Errorf("insert grading system %q: %w", name, err)
		}
		id, err := res.LastInsertId()
		if err != nil {
			return 0, fmt.Errorf("last insert id for grading system %q: %w", name, err)
		}
		return id, nil
	default:
		return 0, fmt.Errorf("lookup grading system %q: %w", name, err)
	}
}

// ensureRank inserts the rank for one belt-and-degree if it is not already
// present, and corrects the name of one that is. The lookup is on the natural key
// (grading_system_id, rank_group, degree), never on the name: the name is a
// display-shaped string that nothing keeps stable, and respelling it under a
// name lookup inserted a second row for a rank promotions already pointed at.
// sort_order is left as found, so a re-seed neither duplicates nor reorders.
//
// The natural key is deliberately not a unique index. Migration 00002 leaves
// rank_group empty and degree zero where a system defines no such dimension, so
// a system of named steps would put every rank on the same pair and an index
// would admit one of them. This lookup makes the same assumption and would skip
// the rest — the difference being that it is code, which whoever adds such a
// system rewrites along with seedSystems, while an index would survive silently.
func ensureRank(tx *sql.Tx, gsID int64, belt string, degree, order int) error {
	name := rankName(belt, degree)
	var id int64
	var stored string
	err := tx.QueryRow(
		`SELECT id, name FROM ranks WHERE grading_system_id = ? AND rank_group = ? AND degree = ?`,
		gsID, belt, degree,
	).Scan(&id, &stored)
	switch {
	case err == nil:
		if stored == name {
			return nil // already seeded
		}
		if _, err := tx.Exec(`UPDATE ranks SET name = ? WHERE id = ?`, name, id); err != nil {
			return fmt.Errorf("rename rank %q to %q: %w", stored, name, err)
		}
		return nil
	case errors.Is(err, sql.ErrNoRows):
		_, err := tx.Exec(
			`INSERT INTO ranks (grading_system_id, name, rank_group, degree, sort_order)
			 VALUES (?, ?, ?, ?, ?)`,
			gsID, name, belt, degree, order,
		)
		if err != nil {
			return fmt.Errorf("insert rank %q: %w", name, err)
		}
		return nil
	default:
		return fmt.Errorf("lookup rank %q: %w", name, err)
	}
}

// rankName renders a name for a belt at a given stripe degree, e.g. "White"
// (plain belt), "White, 1 stripe", "White, 2 stripes". The name is what a
// promotion targets; group/degree are the descriptive breakdown.
//
// It stays English, and must not be localized (ADR-0009): what a trainer reads is
// composed in the view, and this string is only the fallback for a rank the view
// cannot compose. Respelling it no longer duplicates ranks (see ensureRank), but
// cmd/organizer/demo.go still addresses its target ranks by these names.
func rankName(belt string, degree int) string {
	switch degree {
	case 0:
		return belt
	case 1:
		return belt + ", 1 stripe"
	default:
		return fmt.Sprintf("%s, %d stripes", belt, degree)
	}
}
